// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7de6c3dd94feaeb21f20054b9f30d5dabc5efabd/mocha/mocha-node.d.ts
declare module 'mocha-node' {
// Type definitions for mocha 2.2.5
// Project: http://mochajs.org/
// Definitions by: Vadim Macagon <https://github.com/enlight>, vvakame <https://github.com/vvakame>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped


namespace Mocha {
    interface IRunnable extends NodeJS.EventEmitter {
    }
    interface ISuite extends NodeJS.EventEmitter {
    }
    interface IRunner extends NodeJS.EventEmitter {
    }
}
}
